[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl_1_1"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "export PRISMA_BINARY_TARGET=linux-musl",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm run start"