[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[phases.start]
cmd = "npm run prisma:migrate && npm run start"